(use-modules (ice-9 rdelim)
	     (custom processes))

(define x #false)
(with-opened-subprocess (fork-and-exec '(cat -))
			(lambda ()
			  (write-line "hello!")
			  (close-output-port (current-output-port))
			  (set! x (read-line))))
(display x)
(newline)
